<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Event;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFlagships() {
        return $this->findBy([ 'type' => Event::TYPE_FLAGSHIP ]);
    }

    public function getCelebrityAppearances() {
        return $this->findBy([ 'type' => Event::TYPE_CELEBRITY_APPEARANCE ]);
    }

    public function getWorkshops() {
        return $this->findBy([ 'type' => Event::TYPE_WORKSHOP ]);
    }

    public function getGuestLectures() {
        return $this->findBy([ 'type' => Event::TYPE_GUEST_LECTURE ]);
    }
}
