<?php

namespace AppBundle\Repository;

/**
 * UserEventParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEventParticipationRepository extends \Doctrine\ORM\EntityRepository
{
}
