imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: proxy.yml }
    - { resource: '@UserBundle/Resources/config/services.yml' }
# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en_IN
    site_hostname:  'perception.cetb.in'
    site_name:  'Perception 2017'
    mail_sender_host: '%%site_hostname%'
    mail_sender_name: '%%site_name%'
    facebook_app_id: '1711046969206430'
    facebook_app_secret: '163fe062666ce088bc2a2d21acc24b9a'
    google_app_id: '95691328307-oi3iiuif4rin861imvdh9ro0mpfdhrq8.apps.googleusercontent.com'
    google_app_secret: 'P_hTWem1N6hOwvptIPpEJzHE'
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - 'RecaptchaBundle:Form:fields.html.twig'


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8mb4
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    encryption: "%mailer_encryption%"
    spool:     { type: memory }

vich_uploader:
    db_driver: orm
    mappings:
        upload_image:
            uri_prefix:         /uploads/images
            upload_destination: '%kernel.root_dir%/../web/uploads/images'
            delete_on_remove: true # whether to delete file upon removal of entity
            inject_on_load: true # whether to inject a File upon load

recaptcha:
    site_key: '6Ld1zhAUAAAAANmsluLvgmqLvoHbKoUoxTn9np9O'
    secret_key: '6Ld1zhAUAAAAAKkcttgYAgUWG_WfBT3Joo3C0oP5'

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    workers:
        cache_busting: ~
    filters:
        cssrewrite: ~

doctrine_cache:
    providers:
        md_cache:
          type: 'file_system'
          namespace: 'md_html'