# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    event_manager:
        class: AppBundle\Service\EventManager
        arguments: ["@doctrine.orm.entity_manager"]
