<?php
/**
 * Copyright (c) 2016. Lecturenotes.in
 * Proprietary and confidential
 */

namespace UserBundle\Repository;

/**
 * RememberMeSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RememberMeSessionRepository extends \Doctrine\ORM\EntityRepository
{

}
